name: Docs Enhancement
description: Improve documentation structure, content, or automation.
title: "[Docs] "
labels:
  - documentation
body:
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Add checkboxes below (copy-paste `- [ ] Task`)
      placeholder: "- [ ] Update CONTRIBUTING.md"
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the problem or changes needed
      placeholder: Link repo docs to the central wiki.
    validations:
      required: true
  - type: checkboxes  
    id: reminders  
    attributes:  
      label: Reminders  
      description: Check these before marking the issue as done.  
      options:  
        - label: Create branch for this issue
        - label: Verify cross-repo links  
        - label: Link ADR if necessary